name: Shell Workflow

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: List directories
        run: ls
      - name: List all directories (-a)
        run: ls -a
